plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'jacoco'
    id 'com.adarshr.test-logger' version '4.0.0'
    id 'io.freefair.lombok' version '9.5.0'
}

group = 'com.kkasztel'
version = '0.7.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.14.4'
    junitLauncherVersion = '1.14.4'
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junitVersion"
    testImplementation "org.junit.platform:junit-platform-launcher:$junitLauncherVersion"
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
    reports {
        html.required = true
        junitXml.required = true
    }
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
    classDirectories.setFrom files(classDirectories.files.collect {
        fileTree(dir: it, exclude: ['**/generated/**'])
    })
    executionData.setFrom fileTree(layout.buildDirectory).include("**/jacoco/test.exec")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name = 'utils'
                description = 'Utility library by kacperkasztelanic'
                url = 'https://github.com/kacperkasztelanic/utils'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'kacperkasztelanic'
                        name = 'Kacper Kasztelanic'
                    }
                }

                scm {
                    connection = 'scm:git:git://github.com/kacperkasztelanic/utils.git'
                    developerConnection = 'scm:git:ssh://github.com:kacperkasztelanic/utils.git'
                    url = 'https://github.com/kacperkasztelanic/utils'
                }
            }
        }
    }

    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/kacperkasztelanic/utils')
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

if (project.findProperty("signing") == "true") {
    signing {
        useGpgCmd()
        sign publishing.publications.mavenJava
    }
}
